/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.SwingUtilities;

import BendaGeometri.BelahKetupat;
import BendaGeometri.JajaranGenjang;
import BendaGeometri.JuringLingkaran;
import BendaGeometri.LayangLayang;
import BendaGeometri.Lingkaran;
import BendaGeometri.Persegi;
import BendaGeometri.PersegiPanjang;
import BendaGeometri.Segitiga;
import BendaGeometri.TemberengLingkaran;
import BendaGeometri.Trapesium;

/**
 *
 * @author ASUS
 */
public class Benda2DGUI extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public Benda2DGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        segitigaButton = new javax.swing.JButton();
        persegiButton = new javax.swing.JButton();
        persegiPanjangButton = new javax.swing.JButton();
        jajaranGenjangButton = new javax.swing.JButton();
        trapesiumButton = new javax.swing.JButton();
        belahKetupatButton = new javax.swing.JButton();
        layangLayangButton = new javax.swing.JButton();
        lingkaranButton = new javax.swing.JButton();
        temberengLingkaranButton = new javax.swing.JButton();
        juringLingkaranButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(30, 75, 112));

        homeButton.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.diff.sidebar.changed.color"));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/icons8-home-50.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(homeButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(homeButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 70, 605);

        jPanel1.setBackground(new java.awt.Color(31, 85, 72));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu 2D");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 40, 220, 73);

        jPanel4.setBackground(new java.awt.Color(142, 88, 65));

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        segitigaButton.setBackground(new java.awt.Color(31, 85, 72));
        segitigaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        segitigaButton.setForeground(new java.awt.Color(255, 255, 255));
        segitigaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/segitiga.png"))); // NOI18N
        segitigaButton.setText("Segitiga");
        segitigaButton.setBorder(null);
        segitigaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        segitigaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        segitigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segitigaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(segitigaButton);

        persegiButton.setBackground(new java.awt.Color(31, 85, 72));
        persegiButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        persegiButton.setForeground(new java.awt.Color(255, 255, 255));
        persegiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/persegi.png"))); // NOI18N
        persegiButton.setText("Persegi");
        persegiButton.setBorder(null);
        persegiButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        persegiButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        persegiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persegiButtonActionPerformed(evt);
            }
        });
        jPanel3.add(persegiButton);

        persegiPanjangButton.setBackground(new java.awt.Color(31, 85, 72));
        persegiPanjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        persegiPanjangButton.setForeground(new java.awt.Color(255, 255, 255));
        persegiPanjangButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/PersegiPanjang.png"))); // NOI18N
        persegiPanjangButton.setText("Persegi Panjang");
        persegiPanjangButton.setBorder(null);
        persegiPanjangButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        persegiPanjangButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        persegiPanjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persegiPanjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(persegiPanjangButton);

        jajaranGenjangButton.setBackground(new java.awt.Color(31, 85, 72));
        jajaranGenjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jajaranGenjangButton.setForeground(new java.awt.Color(255, 255, 255));
        jajaranGenjangButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/JajaranGenjang.png"))); // NOI18N
        jajaranGenjangButton.setText("Jajaran Genjang");
        jajaranGenjangButton.setBorder(null);
        jajaranGenjangButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jajaranGenjangButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jajaranGenjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jajaranGenjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jajaranGenjangButton);

        trapesiumButton.setBackground(new java.awt.Color(31, 85, 72));
        trapesiumButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        trapesiumButton.setForeground(new java.awt.Color(255, 255, 255));
        trapesiumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/Trapesium.png"))); // NOI18N
        trapesiumButton.setText("Trapesium");
        trapesiumButton.setBorder(null);
        trapesiumButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trapesiumButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        trapesiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapesiumButtonActionPerformed(evt);
            }
        });
        jPanel3.add(trapesiumButton);

        belahKetupatButton.setBackground(new java.awt.Color(31, 85, 72));
        belahKetupatButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        belahKetupatButton.setForeground(new java.awt.Color(255, 255, 255));
        belahKetupatButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/BelahKetupat.png"))); // NOI18N
        belahKetupatButton.setText("Belah Ketupat");
        belahKetupatButton.setBorder(null);
        belahKetupatButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        belahKetupatButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        belahKetupatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belahKetupatButtonActionPerformed(evt);
            }
        });
        jPanel3.add(belahKetupatButton);

        layangLayangButton.setBackground(new java.awt.Color(31, 85, 72));
        layangLayangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        layangLayangButton.setForeground(new java.awt.Color(255, 255, 255));
        layangLayangButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/LayangLayang.png"))); // NOI18N
        layangLayangButton.setText("Layang-Layang");
        layangLayangButton.setBorder(null);
        layangLayangButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        layangLayangButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        layangLayangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layangLayangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(layangLayangButton);

        lingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        lingkaranButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lingkaranButton.setForeground(new java.awt.Color(255, 255, 255));
        lingkaranButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/Lingkaran.png"))); // NOI18N
        lingkaranButton.setText("Lingkaran");
        lingkaranButton.setBorder(null);
        lingkaranButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lingkaranButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(lingkaranButton);

        temberengLingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        temberengLingkaranButton.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        temberengLingkaranButton.setForeground(new java.awt.Color(255, 255, 255));
        temberengLingkaranButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/TemberengLingkaran.png"))); // NOI18N
        temberengLingkaranButton.setText("Tembereng Lingkaran");
        temberengLingkaranButton.setBorder(null);
        temberengLingkaranButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        temberengLingkaranButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        temberengLingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temberengLingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(temberengLingkaranButton);

        juringLingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        juringLingkaranButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        juringLingkaranButton.setForeground(new java.awt.Color(255, 255, 255));
        juringLingkaranButton
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("../Assets/Images/JuringLingkaran.png"))); // NOI18N
        juringLingkaranButton.setText("Juring Lingkaran");
        juringLingkaranButton.setBorder(null);
        juringLingkaranButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        juringLingkaranButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        juringLingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juringLingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(juringLingkaranButton);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 946,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 414,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE)));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 142, 980, 448);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1000, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 470, Short.MAX_VALUE));

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 130, 1000, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(73, 0, 1000, 600);

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu ui = new MainMenu();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }

    private void segitigaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialAlas = 5.0;
        double initialTinggi = 4.0;
        double initialSisiMiring1 = 6.0;
        double initialSisiMiring2 = 7.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            Segitiga s = new Segitiga(values[0], values[1], values[2], values[3]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Alas: %.2f, Tinggi: %.2f, Sisi Miring 1: %.2f, Sisi Miring 2: %.2f",
                            values[0], values[1], values[2], values[3]),
                    s.menghitungLuas(),
                    s.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Segitiga",
                new String[] { "Alas", "Tinggi", "Sisi Miring 1", "Sisi Miring 2" },
                new double[] { initialAlas, initialTinggi, initialSisiMiring1, initialSisiMiring2 },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                Segitiga s = new Segitiga(values[0], values[1], values[2], values[3]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Alas: %.2f, Tinggi: %.2f, Sisi Miring 1: %.2f, Sisi Miring 2: %.2f",
                                values[0], values[1], values[2], values[3]),
                        s.menghitungLuas(values[0], values[1]),
                        s.menghitungKeliling(values[0], values[2], values[3]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Segitiga",
                        new String[] { "Alas", "Tinggi", "Sisi Miring 1", "Sisi Miring 2" },
                        new double[] { initialAlas, initialTinggi, initialSisiMiring1, initialSisiMiring2 },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void persegiButtonActionPerformed(java.awt.event.ActionEvent evt) {
        double initialSisi = 5.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            Persegi p = new Persegi(values[0]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Sisi: %.2f", values[0]),
                    p.menghitungLuas(),
                    p.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Persegi",
                new String[] { "Sisi" },
                new double[] { initialSisi },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                Persegi p = new Persegi(values[0]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Sisi: %.2f", values[0]),
                        p.menghitungLuas(values[0]),
                        p.menghitungKeliling(values[0]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Persegi",
                        new String[] { "Sisi" },
                        new double[] { initialSisi },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void persegiPanjangButtonActionPerformed(java.awt.event.ActionEvent evt) {
        double initialPanjang = 5.0;
        double initialLebar = 3.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            PersegiPanjang pp = new PersegiPanjang(values[0], values[1]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Panjang: %.2f, Lebar: %.2f", values[0], values[1]), // Fixed: Added comma separator
                    pp.menghitungLuas(),
                    pp.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Persegi Panjang",
                new String[] { "Panjang", "Lebar" },
                new double[] { initialPanjang, initialLebar },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                PersegiPanjang pp = new PersegiPanjang(values[0], values[1]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Panjang: %.2f, Lebar: %.2f", values[0], values[1]), // Fixed: Added comma
                                                                                           // separator
                        pp.menghitungLuas(values[0], values[1]),
                        pp.menghitungKeliling(values[0], values[1]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Persegi Panjang",
                        new String[] { "Panjang", "Lebar" },
                        new double[] { initialPanjang, initialLebar },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void jajaranGenjangButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialAlas = 6.0;
        double initialTinggi = 4.0;
        double initialSisiMiring = 5.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            JajaranGenjang jg = new JajaranGenjang(values[0], values[1], values[2]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Alas: %.2f, Tinggi: %.2f, Sisi Miring: %.2f",
                            values[0], values[1], values[2]),
                    jg.menghitungLuas(),
                    jg.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Jajaran Genjang",
                new String[] { "Alas", "Tinggi", "Sisi Miring" },
                new double[] { initialAlas, initialTinggi, initialSisiMiring },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                JajaranGenjang jg = new JajaranGenjang(values[0], values[1], values[2]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Alas: %.2f, Tinggi: %.2f, Sisi Miring: %.2f",
                                values[0], values[1], values[2]),
                        jg.menghitungLuas(values[0], values[1]),
                        jg.menghitungKeliling(values[0], values[2]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Jajaran Genjang",
                        new String[] { "Alas", "Tinggi", "Sisi Miring" },
                        new double[] { initialAlas, initialTinggi, initialSisiMiring },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void trapesiumButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialAlasAtas = 4.0;
        double initialAlasBawah = 8.0;
        double initialTinggi = 5.0;
        double initialSisiMiringKiri = 6.0;
        double initialSisiMiringKanan = 6.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            Trapesium t = new Trapesium(values[0], values[1], values[2], values[3], values[4]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format(
                            "Alas Atas: %.2f, Alas Bawah: %.2f, Tinggi: %.2f, Sisi Miring Kiri: %.2f, Sisi Miring Kanan: %.2f",
                            values[0], values[1], values[2], values[3], values[4]),
                    t.menghitungLuas(),
                    t.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Trapesium",
                new String[] { "Alas Atas", "Alas Bawah", "Tinggi", "Sisi Miring Kiri", "Sisi Miring Kanan" },
                new double[] { initialAlasAtas, initialAlasBawah, initialTinggi, initialSisiMiringKiri,
                        initialSisiMiringKanan },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                Trapesium t = new Trapesium(values[0], values[1], values[2], values[3], values[4]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format(
                                "Alas Atas: %.2f, Alas Bawah: %.2f, Tinggi: %.2f, Sisi Miring Kiri: %.2f, Sisi Miring Kanan: %.2f",
                                values[0], values[1], values[2], values[3], values[4]),
                        t.menghitungLuas(values[0], values[1], values[2]),
                        t.menghitungKeliling(values[0], values[1], values[3], values[4]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Trapesium",
                        new String[] { "Alas Atas", "Alas Bawah", "Tinggi", "Sisi Miring Kiri", "Sisi Miring Kanan" },
                        new double[] { initialAlasAtas, initialAlasBawah, initialTinggi, initialSisiMiringKiri,
                                initialSisiMiringKanan },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void belahKetupatButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialDiagonal1 = 8.0;
        double initialDiagonal2 = 6.0;
        double initialSisi = 5.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            BelahKetupat bk = new BelahKetupat(values[0], values[1], values[2]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Diagonal 1: %.2f, Diagonal 2: %.2f, Sisi: %.2f",
                            values[0], values[1], values[2]),
                    bk.menghitungLuas(),
                    bk.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Belah Ketupat",
                new String[] { "Diagonal 1", "Diagonal 2", "Sisi" },
                new double[] { initialDiagonal1, initialDiagonal2, initialSisi },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                BelahKetupat bk = new BelahKetupat(values[0], values[1], values[2]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Diagonal 1: %.2f, Diagonal 2: %.2f, Sisi: %.2f",
                                values[0], values[1], values[2]),
                        bk.menghitungLuas(values[0], values[1]),
                        bk.menghitungKeliling(values[2]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Belah Ketupat",
                        new String[] { "Diagonal 1", "Diagonal 2", "Sisi" },
                        new double[] { initialDiagonal1, initialDiagonal2, initialSisi },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void layangLayangButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialDiagonal1 = 10.0;
        double initialDiagonal2 = 6.0;
        double initialSisiPendek = 5.0;
        double initialSisiPanjang = 8.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            LayangLayang ll = new LayangLayang(values[0], values[1], values[2], values[3]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Diagonal 1: %.2f, Diagonal 2: %.2f, Sisi Pendek: %.2f, Sisi Panjang: %.2f",
                            values[0], values[1], values[2], values[3]),
                    ll.menghitungLuas(),
                    ll.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Layang-layang",
                new String[] { "Diagonal 1", "Diagonal 2", "Sisi Pendek", "Sisi Panjang" },
                new double[] { initialDiagonal1, initialDiagonal2, initialSisiPendek, initialSisiPanjang },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                LayangLayang ll = new LayangLayang(values[0], values[1], values[2], values[3]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Diagonal 1: %.2f, Diagonal 2: %.2f, Sisi Pendek: %.2f, Sisi Panjang: %.2f",
                                values[0], values[1], values[2], values[3]),
                        ll.menghitungLuas(values[0], values[1]),
                        ll.menghitungKeliling(values[2], values[3]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Layang-layang",
                        new String[] { "Diagonal 1", "Diagonal 2", "Sisi Pendek", "Sisi Panjang" },
                        new double[] { initialDiagonal1, initialDiagonal2, initialSisiPendek, initialSisiPanjang },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void lingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialRadius = 7.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            Lingkaran l = new Lingkaran(values[0]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Radius: %.2f", values[0]),
                    l.menghitungLuas(),
                    l.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Lingkaran",
                new String[] { "Radius" },
                new double[] { initialRadius },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                Lingkaran l = new Lingkaran(values[0]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Radius: %.2f", values[0]),
                        l.menghitungLuas(values[0]),
                        l.menghitungKeliling(values[0]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Lingkaran",
                        new String[] { "Radius" },
                        new double[] { initialRadius },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void temberengLingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialRadius = 10.0;
        double initialSudut = 60.0;

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            TemberengLingkaran tl = new TemberengLingkaran(values[0], values[1]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Radius: %.2f, Sudut: %.2f°", values[0], values[1]),
                    tl.menghitungLuas(),
                    tl.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Tembereng Lingkaran",
                new String[] { "Radius", "Sudut" },
                new double[] { initialRadius, initialSudut },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                TemberengLingkaran tl = new TemberengLingkaran(values[0], values[1]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Radius: %.2f, Sudut: %.2f°", values[0], values[1]),
                        tl.menghitungLuas(values[0], values[1]),
                        tl.menghitungKeliling(values[0], values[1]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Tembereng Lingkaran",
                        new String[] { "Radius", "Sudut" },
                        new double[] { initialRadius, initialSudut },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    private void juringLingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        double initialRadius = 8.0;
        double initialSudutJuring = 90.0; // dalam derajat

        DialogPerhitunganStatis.KalkulatorBentuk staticCalculator = values -> {
            JuringLingkaran jl = new JuringLingkaran(values[0], values[1]);
            return new DialogPerhitunganStatis.HasilPerhitungan(
                    String.format("Radius: %.2f, Sudut Juring: %.2f°", values[0], values[1]),
                    jl.menghitungLuas(),
                    jl.menghitungKeliling());
        };

        DialogPerhitunganStatis staticDialog = new DialogPerhitunganStatis(
                this,
                "Juring Lingkaran",
                new String[] { "Radius", "Sudut Juring (derajat)" },
                new double[] { initialRadius, initialSudutJuring },
                staticCalculator);

        staticDialog.setVisible(true);

        if (staticDialog.apakahLanjutKeDinamis()) {
            DialogPerhitunganStatis.KalkulatorBentuk dynamicCalculator = values -> {
                JuringLingkaran jl = new JuringLingkaran(values[0], values[1]);
                return new DialogPerhitunganStatis.HasilPerhitungan(
                        String.format("Radius: %.2f, Sudut Juring: %.2f°", values[0], values[1]),
                        jl.menghitungLuas(values[0], values[1]),
                        jl.menghitungKeliling(values[0], values[1]));
            };

            SwingUtilities.invokeLater(() -> {
                DialogPerhitunganDinamis dynamicDialog = new DialogPerhitunganDinamis(
                        this,
                        "Juring Lingkaran",
                        new String[] { "Radius", "Sudut Juring (derajat)" },
                        new double[] { initialRadius, initialSudutJuring },
                        dynamicCalculator);
                dynamicDialog.setVisible(true);
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Benda2DGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton belahKetupatButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jajaranGenjangButton;
    private javax.swing.JButton juringLingkaranButton;
    private javax.swing.JButton layangLayangButton;
    private javax.swing.JButton lingkaranButton;
    private javax.swing.JButton persegiButton;
    private javax.swing.JButton persegiPanjangButton;
    private javax.swing.JButton segitigaButton;
    private javax.swing.JButton temberengLingkaranButton;
    private javax.swing.JButton trapesiumButton;
    // End of variables declaration//GEN-END:variables
}
