/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ASUS
 */
public class Benda3DGUI extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public Benda3DGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        prismaSegitigaButton = new javax.swing.JButton();
        limasSegitigaButton = new javax.swing.JButton();
        prismaPersegiButton = new javax.swing.JButton();
        limasPersegiButton = new javax.swing.JButton();
        prismaPersegiPanjangButton = new javax.swing.JButton();
        limasPersegiPanjangButton = new javax.swing.JButton();
        prismaJajaranGenjangButton = new javax.swing.JButton();
        limasJajaranGenjangButton = new javax.swing.JButton();
        prismaTrapesiumButton = new javax.swing.JButton();
        limasTrapesiumButton = new javax.swing.JButton();
        prismaBelahKetupatButton = new javax.swing.JButton();
        limasBelahKetupatButton = new javax.swing.JButton();
        prismaLayangLayangButton = new javax.swing.JButton();
        limasLayangLayangButton = new javax.swing.JButton();
        tabungButton = new javax.swing.JButton();
        kerucutButton = new javax.swing.JButton();
        kerucutTerpancungButton = new javax.swing.JButton();
        bolaButton = new javax.swing.JButton();
        temberengBolaButton = new javax.swing.JButton();
        juringBolaButton = new javax.swing.JButton();
        cincinBolaButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(30, 75, 112));

        homeButton.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.diff.sidebar.changed.color"));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/icons8-home-50.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 70, 605);

        jPanel1.setBackground(new java.awt.Color(31, 85, 72));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Menu 3D");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 40, 220, 73);

        jPanel4.setBackground(new java.awt.Color(142, 88, 65));

        jPanel3.setBackground(new java.awt.Color(31, 85, 72));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        prismaSegitigaButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaSegitigaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaSegitigaButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaSegitigaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaSegitigaButton.setBorder(null);
        prismaSegitigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaSegitigaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaSegitigaButton);

        limasSegitigaButton.setBackground(new java.awt.Color(31, 85, 72));
        limasSegitigaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasSegitigaButton.setForeground(new java.awt.Color(0, 0, 0));
        limasSegitigaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasSegitigaButton.setBorder(null);
        limasSegitigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasSegitigaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasSegitigaButton);

        prismaPersegiButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaPersegiButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaPersegiButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaPersegiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaPersegiButton.setBorder(null);
        prismaPersegiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaPersegiButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaPersegiButton);

        limasPersegiButton.setBackground(new java.awt.Color(31, 85, 72));
        limasPersegiButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasPersegiButton.setForeground(new java.awt.Color(0, 0, 0));
        limasPersegiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasPersegiButton.setBorder(null);
        limasPersegiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasPersegiButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasPersegiButton);

        prismaPersegiPanjangButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaPersegiPanjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaPersegiPanjangButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaPersegiPanjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaPersegiPanjangButton.setBorder(null);
        prismaPersegiPanjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaPersegiPanjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaPersegiPanjangButton);

        limasPersegiPanjangButton.setBackground(new java.awt.Color(31, 85, 72));
        limasPersegiPanjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasPersegiPanjangButton.setForeground(new java.awt.Color(0, 0, 0));
        limasPersegiPanjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasPersegiPanjangButton.setBorder(null);
        limasPersegiPanjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasPersegiPanjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasPersegiPanjangButton);

        prismaJajaranGenjangButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaJajaranGenjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaJajaranGenjangButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaJajaranGenjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaJajaranGenjangButton.setBorder(null);
        prismaJajaranGenjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaJajaranGenjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaJajaranGenjangButton);

        limasJajaranGenjangButton.setBackground(new java.awt.Color(31, 85, 72));
        limasJajaranGenjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasJajaranGenjangButton.setForeground(new java.awt.Color(0, 0, 0));
        limasJajaranGenjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasJajaranGenjangButton.setBorder(null);
        limasJajaranGenjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasJajaranGenjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasJajaranGenjangButton);

        prismaTrapesiumButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaTrapesiumButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaTrapesiumButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaTrapesiumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaTrapesiumButton.setBorder(null);
        prismaTrapesiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaTrapesiumButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaTrapesiumButton);

        limasTrapesiumButton.setBackground(new java.awt.Color(31, 85, 72));
        limasTrapesiumButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasTrapesiumButton.setForeground(new java.awt.Color(0, 0, 0));
        limasTrapesiumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasTrapesiumButton.setBorder(null);
        limasTrapesiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasTrapesiumButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasTrapesiumButton);

        prismaBelahKetupatButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaBelahKetupatButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaBelahKetupatButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaBelahKetupatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaBelahKetupatButton.setBorder(null);
        prismaBelahKetupatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaBelahKetupatButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaBelahKetupatButton);

        limasBelahKetupatButton.setBackground(new java.awt.Color(31, 85, 72));
        limasBelahKetupatButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasBelahKetupatButton.setForeground(new java.awt.Color(0, 0, 0));
        limasBelahKetupatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasBelahKetupatButton.setBorder(null);
        limasBelahKetupatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasBelahKetupatButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasBelahKetupatButton);

        prismaLayangLayangButton.setBackground(new java.awt.Color(31, 85, 72));
        prismaLayangLayangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        prismaLayangLayangButton.setForeground(new java.awt.Color(0, 0, 0));
        prismaLayangLayangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        prismaLayangLayangButton.setBorder(null);
        prismaLayangLayangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prismaLayangLayangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(prismaLayangLayangButton);

        limasLayangLayangButton.setBackground(new java.awt.Color(31, 85, 72));
        limasLayangLayangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        limasLayangLayangButton.setForeground(new java.awt.Color(0, 0, 0));
        limasLayangLayangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        limasLayangLayangButton.setBorder(null);
        limasLayangLayangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limasLayangLayangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(limasLayangLayangButton);

        tabungButton.setBackground(new java.awt.Color(31, 85, 72));
        tabungButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        tabungButton.setForeground(new java.awt.Color(0, 0, 0));
        tabungButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        tabungButton.setBorder(null);
        tabungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabungButtonActionPerformed(evt);
            }
        });
        jPanel3.add(tabungButton);

        kerucutButton.setBackground(new java.awt.Color(31, 85, 72));
        kerucutButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        kerucutButton.setForeground(new java.awt.Color(0, 0, 0));
        kerucutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        kerucutButton.setBorder(null);
        kerucutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerucutButtonActionPerformed(evt);
            }
        });
        jPanel3.add(kerucutButton);

        kerucutTerpancungButton.setBackground(new java.awt.Color(31, 85, 72));
        kerucutTerpancungButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        kerucutTerpancungButton.setForeground(new java.awt.Color(0, 0, 0));
        kerucutTerpancungButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        kerucutTerpancungButton.setBorder(null);
        kerucutTerpancungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerucutTerpancungButtonActionPerformed(evt);
            }
        });
        jPanel3.add(kerucutTerpancungButton);

        bolaButton.setBackground(new java.awt.Color(31, 85, 72));
        bolaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        bolaButton.setForeground(new java.awt.Color(0, 0, 0));
        bolaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        bolaButton.setBorder(null);
        bolaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(bolaButton);

        temberengBolaButton.setBackground(new java.awt.Color(31, 85, 72));
        temberengBolaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        temberengBolaButton.setForeground(new java.awt.Color(0, 0, 0));
        temberengBolaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        temberengBolaButton.setBorder(null);
        temberengBolaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temberengBolaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(temberengBolaButton);

        juringBolaButton.setBackground(new java.awt.Color(31, 85, 72));
        juringBolaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        juringBolaButton.setForeground(new java.awt.Color(0, 0, 0));
        juringBolaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        juringBolaButton.setBorder(null);
        juringBolaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juringBolaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(juringBolaButton);

        cincinBolaButton.setBackground(new java.awt.Color(31, 85, 72));
        cincinBolaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        cincinBolaButton.setForeground(new java.awt.Color(0, 0, 0));
        cincinBolaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        cincinBolaButton.setBorder(null);
        cincinBolaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincinBolaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cincinBolaButton);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 142, 980, 448);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 130, 1000, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(73, 0, 1000, 600);

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limasSegitigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasSegitigaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasSegitigaButtonActionPerformed

    private void prismaPersegiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaPersegiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaPersegiButtonActionPerformed

    private void limasPersegiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasPersegiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasPersegiButtonActionPerformed

    private void prismaPersegiPanjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaPersegiPanjangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaPersegiPanjangButtonActionPerformed

    private void limasPersegiPanjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasPersegiPanjangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasPersegiPanjangButtonActionPerformed

    private void prismaJajaranGenjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaJajaranGenjangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaJajaranGenjangButtonActionPerformed

    private void limasJajaranGenjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasJajaranGenjangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasJajaranGenjangButtonActionPerformed

    private void prismaTrapesiumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaTrapesiumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaTrapesiumButtonActionPerformed

    private void limasTrapesiumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasTrapesiumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasTrapesiumButtonActionPerformed

    private void prismaBelahKetupatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaBelahKetupatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaBelahKetupatButtonActionPerformed

    private void limasBelahKetupatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasBelahKetupatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasBelahKetupatButtonActionPerformed

    private void prismaLayangLayangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaLayangLayangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaLayangLayangButtonActionPerformed

    private void limasLayangLayangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limasLayangLayangButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limasLayangLayangButtonActionPerformed

    private void tabungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabungButtonActionPerformed

    private void kerucutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerucutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerucutButtonActionPerformed

    private void kerucutTerpancungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerucutTerpancungButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerucutTerpancungButtonActionPerformed

    private void bolaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bolaButtonActionPerformed

    private void temberengBolaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temberengBolaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temberengBolaButtonActionPerformed

    private void juringBolaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juringBolaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juringBolaButtonActionPerformed

    private void cincinBolaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincinBolaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincinBolaButtonActionPerformed

    private void prismaSegitigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prismaSegitigaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prismaSegitigaButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu ui = new MainMenu();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Benda3DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Benda3DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Benda3DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Benda3DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Benda3DGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bolaButton;
    private javax.swing.JButton cincinBolaButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton juringBolaButton;
    private javax.swing.JButton kerucutButton;
    private javax.swing.JButton kerucutTerpancungButton;
    private javax.swing.JButton limasBelahKetupatButton;
    private javax.swing.JButton limasJajaranGenjangButton;
    private javax.swing.JButton limasLayangLayangButton;
    private javax.swing.JButton limasPersegiButton;
    private javax.swing.JButton limasPersegiPanjangButton;
    private javax.swing.JButton limasSegitigaButton;
    private javax.swing.JButton limasTrapesiumButton;
    private javax.swing.JButton prismaBelahKetupatButton;
    private javax.swing.JButton prismaJajaranGenjangButton;
    private javax.swing.JButton prismaLayangLayangButton;
    private javax.swing.JButton prismaPersegiButton;
    private javax.swing.JButton prismaPersegiPanjangButton;
    private javax.swing.JButton prismaSegitigaButton;
    private javax.swing.JButton prismaTrapesiumButton;
    private javax.swing.JButton tabungButton;
    private javax.swing.JButton temberengBolaButton;
    // End of variables declaration//GEN-END:variables
}
