/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import BendaGeometri.*;

/**
 *
 * @author ASUS
 */
public class BendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    private JPanel loopPanel;
    private JPanel frameBawah;
    private JPanel sidebar;

    public BendaGUI(Benda2D benda) {
        initComponents();
        String namaBenda = benda.getNamaBenda();
        namaLabel.setText("Benda " + namaBenda);
        luasLabel.setText("Luas " + namaBenda + " " + benda.menghitungLuas() + " cm2");
        kelilingLabel.setText("Keliling " +  namaBenda + " " + benda.menghitungKeliling() + " cm");
        luasLabel2.setText("<html> Apakah Anda ingin Mengubah Nilai ?Params dari " + namaBenda + " </html>");
        setLayout(new BorderLayout());

        loopPanel = new JPanel();
        frameBawah = new JPanel();
        sidebar = new JPanel();

        // Atur tata letak frameBawah ke null
        frameBawah.setLayout(null);

        // Atur warna sidebar
        sidebar.setBackground(new Color(30, 75, 112));

        // Atur tata letak loopPanel ke GridLayout
        loopPanel.setLayout(new GridLayout(0, 2));
        loopPanel.setBackground(Color.WHITE);
        loopPanel.setForeground(Color.BLACK);
        int jumlahField = 5;
        for (int i = 1; i <= jumlahField; i++) {
            JLabel label = new JLabel("Input " + i + ":");
            loopPanel.add(label);

            JTextField textField = new JTextField();
            loopPanel.add(textField);
        }

        // Tambahkan loopPanel ke frameBawah
        loopPanel.setBounds(70, 0, 300, 100); // Atur posisi dan ukuran loopPanel
        frameBawah.add(loopPanel);

        // Tambahkan sidebar ke frameBawah
        frameBawah.add(sidebar);

        // Tambahkan frameBawah ke JFrame di BorderLayout.SOUTH
        add(frameBawah, BorderLayout.SOUTH);

        // Tambahkan listener untuk mengatur tinggi sidebar setelah frame ditampilkan
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                sidebar.setBounds(0, 0, 70, frameBawah.getHeight());
                frameBawah.setPreferredSize(new Dimension(frameBawah.getWidth(), 100)); //Atur tinggi frameBawah
                frameBawah.revalidate();
                frameBawah.repaint();
            }
        });

        // Atur ukuran frameBawah secara manual
        frameBawah.setPreferredSize(new Dimension(getWidth(), 100));

        revalidate();
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        luasLabel = new javax.swing.JLabel();
        kelilingLabel = new javax.swing.JLabel();
        luasLabel2 = new javax.swing.JLabel();
        tidakButton = new javax.swing.JButton();
        yaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(30, 75, 112));

        homeButton.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.diff.sidebar.changed.color"));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/icons8-home-50.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 70, 370);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        namaLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLabel.setText("Benda ?Segitiga");

        luasLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        luasLabel.setForeground(new java.awt.Color(0, 0, 0));
        luasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luasLabel.setText("Luas ?Segitiga : ?ResultLuas");

        kelilingLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        kelilingLabel.setForeground(new java.awt.Color(0, 0, 0));
        kelilingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelilingLabel.setText("Keliling ?Segitiga : ?ResultKeliling");

        luasLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        luasLabel2.setForeground(new java.awt.Color(0, 0, 0));
        luasLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        luasLabel2.setText("<html> Apakah Anda ingin Mengubah Nilai ?Params </html> :");

        tidakButton.setBackground(new java.awt.Color(199, 84, 80));
        tidakButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tidakButton.setForeground(new java.awt.Color(255, 255, 255));
        tidakButton.setText("Tidak");

        yaButton.setBackground(new java.awt.Color(98, 181, 66));
        yaButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        yaButton.setForeground(new java.awt.Color(255, 255, 255));
        yaButton.setText("Ya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tidakButton))
                    .addComponent(kelilingLabel)
                    .addComponent(luasLabel)
                    .addComponent(luasLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelilingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(luasLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidakButton)
                    .addComponent(yaButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(73, 0, 540, 370);

        setSize(new java.awt.Dimension(627, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu ui = new MainMenu();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                BendaGUI ui = new BendaGUI();
//                ui.setLocationRelativeTo(null);
//                ui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kelilingLabel;
    private javax.swing.JLabel luasLabel;
    private javax.swing.JLabel luasLabel2;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton tidakButton;
    private javax.swing.JButton yaButton;
    // End of variables declaration//GEN-END:variables
}
