/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BendaGeometri.PersegiPanjang;

/**
 *
 * @author ASUS
 */
public class Benda2DGUI extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public Benda2DGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        segitigaButton = new javax.swing.JButton();
        persegiButton = new javax.swing.JButton();
        persegiPanjangButton = new javax.swing.JButton();
        jajaranGenjangButton = new javax.swing.JButton();
        trapesiumButton = new javax.swing.JButton();
        belahKetupatButton = new javax.swing.JButton();
        layangLayangButton = new javax.swing.JButton();
        lingkaranButton = new javax.swing.JButton();
        temberengLingkaranButton = new javax.swing.JButton();
        juringLingkaranButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(30, 75, 112));

        homeButton.setBackground(javax.swing.UIManager.getDefaults().getColor("nb.diff.sidebar.changed.color"));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/icons8-home-50.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 70, 605);

        jPanel1.setBackground(new java.awt.Color(31, 85, 72));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Menu 2D");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 40, 220, 73);

        jPanel4.setBackground(new java.awt.Color(142, 88, 65));

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        segitigaButton.setBackground(new java.awt.Color(31, 85, 72));
        segitigaButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        segitigaButton.setForeground(new java.awt.Color(0, 0, 0));
        segitigaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/segitiga.png"))); // NOI18N
        segitigaButton.setBorder(null);
        segitigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segitigaButtonActionPerformed(evt);
            }
        });
        jPanel3.add(segitigaButton);

        persegiButton.setBackground(new java.awt.Color(31, 85, 72));
        persegiButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        persegiButton.setForeground(new java.awt.Color(0, 0, 0));
        persegiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/persegi.png"))); // NOI18N
        persegiButton.setBorder(null);
        persegiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persegiButtonActionPerformed(evt);
            }
        });
        jPanel3.add(persegiButton);

        persegiPanjangButton.setBackground(new java.awt.Color(31, 85, 72));
        persegiPanjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        persegiPanjangButton.setForeground(new java.awt.Color(0, 0, 0));
        persegiPanjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/PersegiPanjang.png"))); // NOI18N
        persegiPanjangButton.setBorder(null);
        persegiPanjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persegiPanjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(persegiPanjangButton);

        jajaranGenjangButton.setBackground(new java.awt.Color(31, 85, 72));
        jajaranGenjangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jajaranGenjangButton.setForeground(new java.awt.Color(0, 0, 0));
        jajaranGenjangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/JajaranGenjang.png"))); // NOI18N
        jajaranGenjangButton.setBorder(null);
        jajaranGenjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jajaranGenjangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jajaranGenjangButton);

        trapesiumButton.setBackground(new java.awt.Color(31, 85, 72));
        trapesiumButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        trapesiumButton.setForeground(new java.awt.Color(0, 0, 0));
        trapesiumButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/Trapesium.png"))); // NOI18N
        trapesiumButton.setBorder(null);
        trapesiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapesiumButtonActionPerformed(evt);
            }
        });
        jPanel3.add(trapesiumButton);

        belahKetupatButton.setBackground(new java.awt.Color(31, 85, 72));
        belahKetupatButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        belahKetupatButton.setForeground(new java.awt.Color(0, 0, 0));
        belahKetupatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/BelahKetupat.png"))); // NOI18N
        belahKetupatButton.setBorder(null);
        belahKetupatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belahKetupatButtonActionPerformed(evt);
            }
        });
        jPanel3.add(belahKetupatButton);

        layangLayangButton.setBackground(new java.awt.Color(31, 85, 72));
        layangLayangButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        layangLayangButton.setForeground(new java.awt.Color(0, 0, 0));
        layangLayangButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/LayangLayang.png"))); // NOI18N
        layangLayangButton.setBorder(null);
        layangLayangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layangLayangButtonActionPerformed(evt);
            }
        });
        jPanel3.add(layangLayangButton);

        lingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        lingkaranButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lingkaranButton.setForeground(new java.awt.Color(0, 0, 0));
        lingkaranButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/Lingkaran.png"))); // NOI18N
        lingkaranButton.setBorder(null);
        lingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(lingkaranButton);

        temberengLingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        temberengLingkaranButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        temberengLingkaranButton.setForeground(new java.awt.Color(0, 0, 0));
        temberengLingkaranButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/TemberengLingkaran.png"))); // NOI18N
        temberengLingkaranButton.setBorder(null);
        temberengLingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temberengLingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(temberengLingkaranButton);

        juringLingkaranButton.setBackground(new java.awt.Color(31, 85, 72));
        juringLingkaranButton.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        juringLingkaranButton.setForeground(new java.awt.Color(0, 0, 0));
        juringLingkaranButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/JuringLingkaran.png"))); // NOI18N
        juringLingkaranButton.setBorder(null);
        juringLingkaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juringLingkaranButtonActionPerformed(evt);
            }
        });
        jPanel3.add(juringLingkaranButton);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 142, 980, 448);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 130, 1000, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(73, 0, 1000, 600);

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu ui = new MainMenu();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }
    
    private void segitigaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void persegiButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void persegiPanjangButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void jajaranGenjangButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void trapesiumButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void belahKetupatButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void layangLayangButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void lingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void temberengLingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }
    
    private void juringLingkaranButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Benda2DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Benda2DGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton belahKetupatButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jajaranGenjangButton;
    private javax.swing.JButton juringLingkaranButton;
    private javax.swing.JButton layangLayangButton;
    private javax.swing.JButton lingkaranButton;
    private javax.swing.JButton persegiButton;
    private javax.swing.JButton persegiPanjangButton;
    private javax.swing.JButton segitigaButton;
    private javax.swing.JButton temberengLingkaranButton;
    private javax.swing.JButton trapesiumButton;
    // End of variables declaration//GEN-END:variables
}
