/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        polymorphismButton = new javax.swing.JButton();
        twoDButton = new javax.swing.JButton();
        threeDButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        threadPoolButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Main Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        polymorphismButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        polymorphismButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        polymorphismButton.setForeground(new java.awt.Color(255, 255, 255));
        polymorphismButton.setText("Polymorphism");
        getContentPane().add(polymorphismButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 180, 80));

        twoDButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        twoDButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        twoDButton.setForeground(new java.awt.Color(255, 255, 255));
        twoDButton.setText("Benda2D");
        getContentPane().add(twoDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 180, 80));

        threeDButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        threeDButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        threeDButton.setForeground(new java.awt.Color(255, 255, 255));
        threeDButton.setText("Benda3D");
        getContentPane().add(threeDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 180, 80));

        exitButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        exitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 180, 60));

        threadPoolButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        threadPoolButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        threadPoolButton.setForeground(new java.awt.Color(255, 255, 255));
        threadPoolButton.setText("Thread Pool");
        getContentPane().add(threadPoolButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 180, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/SplashScreen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton polymorphismButton;
    private javax.swing.JButton threadPoolButton;
    private javax.swing.JButton threeDButton;
    private javax.swing.JButton twoDButton;
    // End of variables declaration//GEN-END:variables
}
