/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        polymorphismButton = new javax.swing.JButton();
        twoDButton = new javax.swing.JButton();
        threeDButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        threadPoolButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Main Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 160, 210, 55);

        polymorphismButton.setBackground(new java.awt.Color(53, 146, 196));
        polymorphismButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        polymorphismButton.setForeground(new java.awt.Color(255, 255, 255));
        polymorphismButton.setText("Polymorphism");
        polymorphismButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polymorphismButtonActionPerformed(evt);
            }
        });
        getContentPane().add(polymorphismButton);
        polymorphismButton.setBounds(310, 330, 180, 80);

        twoDButton.setBackground(new java.awt.Color(53, 146, 196));
        twoDButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        twoDButton.setForeground(new java.awt.Color(255, 255, 255));
        twoDButton.setText("Benda2D");
        twoDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(twoDButton);
        twoDButton.setBounds(310, 230, 180, 80);

        threeDButton.setBackground(new java.awt.Color(53, 146, 196));
        threeDButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        threeDButton.setForeground(new java.awt.Color(255, 255, 255));
        threeDButton.setText("Benda3D");
        threeDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(threeDButton);
        threeDButton.setBounds(570, 230, 180, 80);

        exitButton.setBackground(new java.awt.Color(199, 84, 80));
        exitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(440, 430, 180, 60);

        threadPoolButton.setBackground(new java.awt.Color(53, 146, 196));
        threadPoolButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        threadPoolButton.setForeground(new java.awt.Color(255, 255, 255));
        threadPoolButton.setText("Thread Pool");
        threadPoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threadPoolButtonActionPerformed(evt);
            }
        });
        getContentPane().add(threadPoolButton);
        threadPoolButton.setBounds(570, 330, 180, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Images/SplashScreen.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 600);

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void twoDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoDButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Benda2DGUI ui = new Benda2DGUI();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }//GEN-LAST:event_twoDButtonActionPerformed

    private void threeDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeDButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Benda3DGUIOLD ui = new Benda3DGUIOLD();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }//GEN-LAST:event_threeDButtonActionPerformed

    private void polymorphismButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polymorphismButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        PolymorphismGUI ui = new PolymorphismGUI();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }//GEN-LAST:event_polymorphismButtonActionPerformed

    private void threadPoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadPoolButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        ThreadGUI ui = new ThreadGUI();
        ui.setLocationRelativeTo(null);
        ui.setVisible(true);
    }//GEN-LAST:event_threadPoolButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0); // Atau dispose();
        }

    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton polymorphismButton;
    private javax.swing.JButton threadPoolButton;
    private javax.swing.JButton threeDButton;
    private javax.swing.JButton twoDButton;
    // End of variables declaration//GEN-END:variables
}
